# -*- coding: utf-8 -*-
"""Dictionary_runner_v8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5VjVLPmYKqsWRPu0jtrh8YCSjKclT_P
"""

# ── CELL 1: MOUNT & INSTALL ────────────────────────────────────────────────────
#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)
# !pip install statsmodels -q
#!pip install regex
#
#import regex as re

"""
**Setup Cell**
---

---



"""

# 1. Select one or more document types (multiple True values allowed)
statements   = True
minutes      = False
conferences  = False
speeches     = False

# 2. Label used in the output filename
RUN_NAME = 'Sharpe'

# 3. Chose start date
START_DATE = None          # ← change to '2011-01-01' to restrict to post-2010

# 4. Normalization
#    'none'       — raw scores, no normalization
#    'wordcount'  — divide each score by the document's word count
#    'zscore'     — expanding-window z-score (mean/std of all meetings up to t)
#    'both'       — word count first, then expanding z-score on top
NORMALIZE = 'both'

#@title Sharpe
# Word lists from Table A2, Sharpe et al. (2022)
pos_Sharpe = """assurance confident exuberant joy prominent Satisfactory unlimited assure constancy facilitate liberal promise Satisfy upbeat
attain constructive faith lucrative prompt Sound upgrade
attractive cooperate favor manageable proper Soundness uplift
auspicious coordinate favorable mediate prosperity Spectacular upside
backing credible feasible mend rally Stabilize upward
befitting decent fervor mindful readily Stable valid
beneficial definitive filial moderation reassure Stable viable
beneficiary deserve flatter onward receptive Steadiness victorious
benefit desirable flourish opportunity reconcile Steady virtuous
benign discern fond optimism refine Stimulate vitality
better distinction foster optimistic reinstate Stimulation warm
bloom distinguish friendly outrun relaxation Subscribe welcome
bolster durability gain outstanding reliable Succeed
boom eager generous overcome relief Success
boost earnest genuine paramount relieve Successful
bountiful ease good particular remarkable Suffice
bright easy happy patience remarkably Suit
buoyant encourage heal patient repair Support
calm encouragement healthy peaceful rescue Supportive
celebrate endorse helpful persuasive resolve Surge
coherent energetic hope pleasant resolved Surpass
comeback engage hopeful please respectable Sweeten
comfort enhance hospitable pleased respite Sympathetic
comfortable enhancement imperative plentiful restoration Sympathy
commend enjoy impetus plenty restore Synthesis
compensate enrichment impress positive revival Temperate
composure enthusiasm impressive potent revive Thorough
concession enthusiastic improve precious ripe Tolerant
concur envision improvement pretty rosy tranquil
conducive excellent inspire progress salutary tremendous
confide exuberance irresistible progressive sanguine undoubtedly
"""

neg_Sharpe = """adverse dim feeble mishap struggle
afflict disappoint feverish negative suffer
alarming disappointment fragile nervousness terrorism
apprehension disaster gloom offensive threat
apprehensive discomfort gloomy painful tragedy
awkward discouragement grim paltry tragic
bad dismal harsh pessimistic trouble
badly disrupt havoc plague turmoil
bitter disruption hit plight unattractive
bleak dissatisfied horrible poor undermine
bug distort hurt recession undesirable
burdensome distortion illegal sank uneasiness
corrosive distress insecurity scandal uneasy
danger doldrums insidious scare unfavorable
daunting downbeat instability sequester unforeseen
deadlock emergency interfere sluggish unprofitable
deficient erode jeopardize slump unrest
depress fail jeopardy sour violent
depression failure lack sputter War
destruction fake languish stagnant
devastation falter loss standstill
"""

# Build lowercase sets for O(1) lookup
pos_Sharpe = set(w.lower() for w in pos_Sharpe.split())
neg_Sharpe = set(w.lower() for w in neg_Sharpe.split())

# ===========================================================================
# NLP FUNCTION — Sharpe et al. (2022)
# ===========================================================================
def NLP(text: str):
    import re
    tokens = [re.sub(r'[^a-z]', '', t.lower()) for t in text.split()]
    tokens = [t for t in tokens if t]

    pos_count = sum(1 for t in tokens if t in pos_Sharpe)
    neg_count = sum(1 for t in tokens if t in neg_Sharpe)

    return pd.Series({
        'sharpe_positive': pos_count,
        'sharpe_negative': neg_count,
        'sharpe_net':      pos_count - neg_count,
    })

"""---"""

# @title Imports
#    Placed between concatenated sources so sentence tokenizers see a clean
#    document boundary. '\n\n' works well; use ' ' to replicate a bare join.
DOC_SEPARATOR = '\n\n'
# 6. (Optional) Override text extraction from a JSON doc dict
def get_text(doc: dict) -> str:
    for field in ('prepared_remarks', 'text', 'content', 'body', 'statement', 'speech'):
        if field in doc and isinstance(doc[field], str):
            return doc[field]
    return ' '.join(str(v) for v in doc.values() if isinstance(v, str))


# ===========================================================================
# CELL 2 — IMPORTS  (do not edit)
# ===========================================================================
import json, os, re
import pandas as pd

# @title Helper Functions

# ===========================================================================
# CELL 2b — TEXT PREPARATION  (do not edit)
#
# prepare_text(combined_texts) -> str
#   Joins multiple source texts with DOC_SEPARATOR so the runner and the
#   normalization cell both operate on identical text. This is the only
#   processing that happens before NLP() — all cleaning, tokenization, and
#   preprocessing lives inside NLP() itself.
# ===========================================================================

def prepare_text(combined_texts: list) -> str:
    return DOC_SEPARATOR.join(combined_texts)


print(f'DOC_SEPARATOR = {DOC_SEPARATOR!r}')

# @title Configuration
# ===========================================================================
# CELL 3 — CONFIG  (do not edit)
# ===========================================================================
BASE             = '/content/drive/My Drive/HEC Thesis'
CALENDAR_PATH    = f'{BASE}/fomc_calendar.csv'
STATEMENTS_DIR   = f'{BASE}/Text Data/structured_json_statements'
MINUTES_DIR      = f'{BASE}/Text Data/structured_json_minutes'
SPEECHES_DIR     = f'{BASE}/Text Data/structured_json_speeches'
CONFERENCES_DIR  = f'{BASE}/Text Data/structured_json'
SPEECH_SUBDIRS   = ['chair', 'vice_chair', 'others']
OUTPUT_DIR       = f'{BASE}/Taylor Rule Data/NLP Output'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Hierarchy: (source, which calendar column is the index date for that source)
HIERARCHY = [
    ('speeches',    'blackout_date'),
    ('minutes',     'minutes_date'),
    ('statements',  'meeting_date'),
    ('conferences', 'meeting_date'),
]
flags = {
    'speeches':    speeches,
    'minutes':     minutes,
    'statements':  statements,
    'conferences': conferences,
}
DIR_MAP = {
    'statements':  STATEMENTS_DIR,
    'minutes':     MINUTES_DIR,
    'speeches':    SPEECHES_DIR,
    'conferences': CONFERENCES_DIR,
}
# FILE_DATE_COL: which calendar column matches the date in the JSON filename.
# All sources are named with the meeting_date, even minutes (whose pub date is ~3wks later).
FILE_DATE_COL = {
    'statements':  'meeting_date',
    'minutes':     'meeting_date',   # files named with meeting_date, not pub date
    'conferences': 'meeting_date',
}

# INDEX_DATE_COL: which calendar column to use as the 'date' index in the output CSV.
# minutes → minutes_date  (the actual publication date, ~3wks after the meeting)
# all others → meeting_date
INDEX_DATE_COL = {src: col for src, col in HIERARCHY}

active_sources = [name for name, _ in HIERARCHY if flags[name]]
if not active_sources:
    raise ValueError('No source selected. Set at least one flag to True in the Setup Cell.')

primary_source   = active_sources[0]
primary_date_col = dict(HIERARCHY)[primary_source]

print(f'Active sources    : {active_sources}')
print(f'Primary source    : {primary_source}  (determines the index date column)')
print(f'Index date column : {INDEX_DATE_COL.get(primary_source, "meeting_date")}')

# ===========================================================================
# CELL 4 — LOAD CALENDAR  (do not edit)
# ===========================================================================
calendar = (
    pd.read_csv(CALENDAR_PATH, parse_dates=['meeting_date', 'minutes_date', 'blackout_date'])
    .sort_values('meeting_date')
    .reset_index(drop=True)
)
for col in ['meeting_date', 'minutes_date', 'blackout_date']:
    calendar[col] = calendar[col].dt.normalize()

# ── Apply date filter ─────────────────────────────────────────────────────
if START_DATE is not None:
    calendar = calendar[calendar['meeting_date'] >= pd.Timestamp(START_DATE)].reset_index(drop=True)
    print(f'Date filter applied: {START_DATE} onwards ({len(calendar)} meetings)')

print(f'Calendar loaded: {len(calendar)} FOMC meetings')

# @title Helper Functions
# ===========================================================================
# CELL 5 — BUILD FILE INDEX  (do not edit)
# ===========================================================================
def _extract_date(fname: str):
    """Return pd.Timestamp from YYYYMMDD in filename, else None."""
    m = re.search(r'(\d{8})', fname)
    if m:
        try:
            return pd.to_datetime(m.group(1), format='%Y%m%d').normalize()
        except ValueError:
            pass
    return None


def _index_directory(directory: str, subdirs=None) -> dict:
    """Return {date: [path, ...]} for all dated JSON files in directory."""
    search_dirs = (
        [os.path.join(directory, s) for s in subdirs] if subdirs else [directory]
    )
    index = {}
    for d in search_dirs:
        if not os.path.exists(d):
            print(f'  Warning: directory not found: {d}')
            continue
        for fname in os.listdir(d):
            if not fname.endswith('.json'):
                continue
            dt = _extract_date(fname)
            if dt is not None:
                index.setdefault(dt, []).append(os.path.join(d, fname))
    return index


def _load_text(paths: list) -> str:
    """Load JSON files and concatenate their text fields."""
    texts = []
    for path in paths:
        with open(path) as f:
            data = json.load(f)
        docs = data if isinstance(data, list) else [data]
        for doc in docs:
            t = get_text(doc).strip()
            if t:
                texts.append(t)
    return ' '.join(texts)


catalogue = {}
for src in active_sources:
    subdirs = SPEECH_SUBDIRS if src == 'speeches' else None
    catalogue[src] = _index_directory(DIR_MAP[src], subdirs)
    print(f'{src:15s}: {len(catalogue[src])} dated files indexed')

#@title Bodies of Text
# ===========================================================================
# CELL 6 — PATH HELPERS + COVERAGE CHECK  (do not edit)
#
# Temporal alignment rules (based on fomc_calendar.csv structure):
# ──────────────────────────────────────────────────────────────────────────
# Each calendar row X corresponds to meeting_date[X].
#
# statements  → released ON meeting_date[X]
#               Store on row X (no lag). The Sentiment Tester's shift(-1)
#               on the dependent variable then aligns statement[X] with
#               decision[X+1]. Correct.
#
# conferences → press conference on meeting_date[X], same logic as statements.
#               Store on row X (no lag).
#
# minutes     → released on minutes_date[X], ~3 weeks AFTER meeting_date[X].
#               Not public before meeting X. Store on row X+1 (lag = 1),
#               meaning they serve as prior info for the NEXT meeting.
#
# speeches    → blackout_date[X] is a few days BEFORE meeting_date[X].
#               Capture speeches in (blackout_date[X-1], blackout_date[X]].
#               These are available before the blackout of meeting X → row X.
# ===========================================================================

# lag=0: store on the row matching this meeting (statement/conference/speeches)
# lag=1: store on the NEXT row (minutes, published after the meeting)
SOURCE_LAG = {
    'statements':  0,
    'conferences': 0,
    'minutes':     1,
    'speeches':    0,
}


def _speech_paths(idx: int) -> list:
    """Speeches in the inter-meeting window ending at blackout_date[X]."""
    upper = calendar.loc[idx, 'blackout_date']
    lower = (
        calendar.loc[idx - 1, 'blackout_date'] if idx > 0
        else pd.Timestamp('1900-01-01')
    )
    if pd.isna(upper):
        return []
    if pd.isna(lower):
        lower = pd.Timestamp('1900-01-01')
    return [
        path
        for dt, file_list in catalogue['speeches'].items()
        if lower < dt <= upper
        for path in file_list
    ]


def _point_paths(idx: int, src: str) -> list:
    """
    Fetch the JSON file for `src` that belongs on calendar row `idx`.

    SOURCE_LAG controls the lookup:
      lag=0 → fetch the file dated at calendar row idx (same meeting)
      lag=1 → fetch the file dated at calendar row idx-1 (previous meeting,
               because the source was published after that meeting ended)
    """
    lag        = SOURCE_LAG.get(src, 0)
    target_idx = idx - lag
    if target_idx < 0:
        return []
    target = calendar.loc[target_idx, FILE_DATE_COL[src]]
    if pd.isna(target):
        return []
    return catalogue[src].get(target, [])


def get_paths(idx: int) -> dict:
    return {
        src: (_speech_paths(idx) if src == 'speeches' else _point_paths(idx, src))
        for src in active_sources
    }


# Coverage diagnostic
diag = []
for idx, row in calendar.iterrows():
    entry = {'meeting_date': row['meeting_date']}
    for src, paths in get_paths(idx).items():
        entry[f'{src}_files'] = len(paths)
    diag.append(entry)

diag_df = pd.DataFrame(diag)
covered = (diag_df[[f'{s}_files' for s in active_sources]].sum(axis=1) > 0).sum()
print(f'Meetings with at least one file: {covered} / {len(calendar)}')
diag_df.head(10)

#@title Apply NLP
# ===========================================================================
# CELL 7 — APPLY NLP  (do not edit)
# ===========================================================================
results = []
skipped = []
from tqdm.notebook import tqdm

for idx, row in tqdm(calendar.iterrows(), total=len(calendar)):
    combined_texts = []
    for src, paths in get_paths(idx).items():
        if not paths:
            continue
        try:
            t = _load_text(paths).strip()
            if t:
                combined_texts.append(t)
        except Exception as e:
            print(f'  Load error [{src}] {row["meeting_date"].date()}: {e}')

    if not combined_texts:
        skipped.append({'meeting_date': row['meeting_date'], 'reason': 'no text found'})
        continue

    try:
        score = NLP(prepare_text(combined_texts))
    except Exception as e:
        print(f'  NLP error {row["meeting_date"].date()}: {e}')
        skipped.append({'meeting_date': row['meeting_date'], 'reason': str(e)})
        continue

    if isinstance(score, pd.Series):
        result_row = score.copy()
    elif isinstance(score, dict):
        result_row = pd.Series(score)
    else:
        result_row = pd.Series({'score': score})

    result_row['date']         = row[INDEX_DATE_COL.get(primary_source, 'meeting_date')]
    result_row['meeting_date'] = row['meeting_date']
    results.append(result_row)

if not results:
    raise RuntimeError('No results. Check that JSON files have parseable dates and text.')

output_df  = pd.DataFrame(results)
fixed_cols = ['date', 'meeting_date']
score_cols = [c for c in output_df.columns if c not in fixed_cols]
output_df  = output_df[fixed_cols + score_cols].sort_values('date').reset_index(drop=True)

if skipped:
    print(f'Skipped {len(skipped)} meeting(s):')
    for s in skipped:
        print(f'  {s["meeting_date"].date()} — {s["reason"]}')

print(f'\nNLP applied to {len(output_df)} meetings')
output_df.head()

#@title Normalization
# ===========================================================================
if NORMALIZE not in ('none', 'wordcount', 'zscore', 'both'):
    raise ValueError(f"NORMALIZE must be 'none', 'wordcount', 'zscore', or 'both'. Got: '{NORMALIZE}'")

normalized_df = output_df.copy()
score_cols    = [c for c in normalized_df.columns if c not in ('date', 'meeting_date')]

if NORMALIZE in ('wordcount', 'both'):
    # Word count is derived from the same prepared text as NLP() received,
    # so the denominator is consistent with whatever preprocessing was applied.
    word_counts = []
    for idx, row in calendar.iterrows():
        combined_texts = []
        for src, paths in get_paths(idx).items():
            if not paths:
                continue
            try:
                t = _load_text(paths).strip()
                if t:
                    combined_texts.append(t)
            except Exception:
                pass
        full_text = prepare_text(combined_texts) if combined_texts else ''
        word_counts.append(len(full_text.split()))

    wc_series = pd.Series(word_counts, index=calendar['meeting_date'])
    normalized_df['word_count'] = normalized_df['meeting_date'].map(wc_series)

    for col in score_cols:
        normalized_df[col] = normalized_df[col] / normalized_df['word_count']

    print('Word-count normalization applied.')

if NORMALIZE in ('zscore', 'both'):
    for col in score_cols:
        expanding_mean = normalized_df[col].expanding().mean().shift(1)
        expanding_std  = normalized_df[col].expanding().std().shift(1)
        normalized_df[col] = (normalized_df[col] - expanding_mean) / expanding_std

    print(f'Expanding z-score normalization applied. '
          f'({normalized_df[score_cols].isna().any(axis=1).sum()} row(s) with NaN due to insufficient history)')

if NORMALIZE == 'none':
    print('No normalization applied.')

#@title Export
# ===========================================================================
normalized_df = normalized_df.drop(columns=['word_count'], errors='ignore')
if START_DATE is None:
    date_tag = '_full'
elif START_DATE == '2011-01-01':
    date_tag = ''
else:
    date_tag = f'_from{START_DATE[:4]}'

output_path = os.path.join(OUTPUT_DIR, f'{RUN_NAME}{date_tag}_{"_".join(active_sources)}_{NORMALIZE}_nlp.csv')
normalized_df.to_csv(output_path, index=False)

print(f'Saved  -> {output_path}')
print(f'Shape  : {output_df.shape[0]} rows x {output_df.shape[1]} columns')
print(f'Columns: {list(output_df.columns)}')
normalized_df